export class Equipment {
    equipmentId!: number; // The ID is optional since it will be generated by the server
    equipmentName!: string;
    equipmentCost!: number;
    venueId!: number;
    imagePath!: string; // Optional property for the image path
  }
  

