export class FoodItem {
    foodItemId!: number; // The ID is optional since it will be generated by the server
    foodItemName!: string;
    foodItemCost!: number;
    venueId!: number;
    imagePath!: string; // Optional property for the image path
  }